### ISSUE TITLE
Feature request: `:sort` support

### ISSUE THREAD

**Issue by mjgpy3** [jaredpar/VsVim#1833] opened 2016-09-21 20:12 UTC
First of all, excellent plugin! This is by far one of the best "spirit-of-vim" in a non-vim IDE tools out there. Hats off to you!

I'm wondering if there are any nuances or reasons why something like the `sort` command couldn't be implemented.

My typical usage for this command looks like (e.g. on `using` statements)
![vim-sort-usage-fin2](https://cloud.githubusercontent.com/assets/1709849/18727327/226aa1b2-8016-11e6-8bfd-b49ea2d88679.gif)

**Comment by jaredpar** [comment] 2016-09-26 16:06
The `sort` command can be implemented.  It's just one of the items I haven't gotten around to yet 😦  

I believe there are some customizations that I couldn't implement because they are function based.  But the simple functionality seems doable.

**Comment by tyrellj** [comment] 2017-01-17 17:00
Same as #601?

**Comment by efimov-denis** [comment] 2017-03-06 12:26
Still isn't available in 2.3.0.0 version?

**Comment by efimov-denis** [comment] 2017-03-06 12:28
Still isn't available in 2.3.0.0 version?

**Comment by jaredpar** [comment] 2018-01-13 21:54
Looks like a dupe of #601

**Closed by jaredpar** 2018-01-13 21:54 UTC
Labels: feature request
