### ISSUE TITLE
Buffers

### ISSUE THREAD

**Issue by prat0088** [jaredpar/VsVim#743] opened 2012-02-03 06:37 UTC
Support for navigating between tabs would be swell:

:bn
:bp
:b Loa*.cs<tab>

**Comment by wererogue** [comment] 2016-05-10 13:55
+1 :)

**Comment by austincrft** [comment] 2017-02-07 17:30
I'd also like to see `:bd` implemented.

I think these should have a higher priority. VS Tabs have more in common with Vim Buffers than Vim Tabs.

**Comment by ricksladkey** [comment] 2018-08-14 19:02
This is a duplicate of issue #612 and can be closed.

**Comment by nbergen** [comment] 2018-08-14 20:00
#612 is closed, and this is the tracking issue per https://github.com/jaredpar/VsVim/issues/993#issuecomment-354666604

**Closed** 2018-08-16 03:18 UTC
Labels: feature request
