### ISSUE TITLE
Visual-block append  does not work 

### ISSUE THREAD

**Issue by idealist1508** [jaredpar/VsVim#1667] opened 2015-09-11 18:08 UTC
Link to vim documentation: http://vimdoc.sourceforge.net/htmldoc/visual.html#v_b_A
I'm sorry: it was a wrong link.

**Comment by jaredpar** [comment] 2015-09-14 05:50
Can you give some specific examples here?  Block insertion is a supported feature.

**Comment by idealist1508** [comment] 2015-09-14 06:21
I have some visualblock selection
![vbi1](https://cloud.githubusercontent.com/assets/4608274/9843155/06a3be5c-5ab8-11e5-926a-23bf7ebc0851.PNG)
then I press ```Aator```
![vbi2](https://cloud.githubusercontent.com/assets/4608274/9843219/8424835c-5ab8-11e5-873a-0edc291fa719.PNG)
and finally I press ```<Esc>```
![vbi3](https://cloud.githubusercontent.com/assets/4608274/9843225/8764fea2-5ab8-11e5-9f08-0b0942ce7740.PNG)

 >Block insertion is a supported feature. 
Yeah, I know. And it is usually sufficient in most cases. But append after end of lines is impossible.

**Comment by jaredpar** [comment] 2015-09-15 03:44
Ah okay.  Yes it appears that append isn't supported but insert is.  Will look at getting append added.

**Comment by sgrassie** [comment] 2017-04-11 12:46
I came here to post this as a bug but a simple search led me here.

**Comment by and-rej** [comment] 2018-06-15 05:18
This appears to be a(nother) duplicate of #1107. 

Support for this command would be fantastic.

**Closed** 2018-06-18 00:59 UTC
Labels: feature request
