### ISSUE TITLE
Conflicting keybinding issues - options panel is empty

### ISSUE THREAD

**Issue by FelixBoers** [jaredpar/VsVim#2434] opened 2018-11-25 20:52 UTC
I've reinstalled my laptop with Visual Studio 2017 Community, ReSharper 2018 and this awesome extension called VsVim (👍). Sadly some keybindings are not getting handled by VsVim but from Visual Studio. The thing I don't understand is, that the `Extras/Options/VsVim/Keyboard` page (which should show conflicting keybindings, if I'm right) is empty.

![image](https://user-images.githubusercontent.com/2909729/48984169-b2f8b700-f0f8-11e8-8021-e16dcd26cfc5.png)

I've again reinstalled everything from scratch but I still see the same empty options page and my keybindings are not getting handled. Some keybindings that are not working are for example:

| Keybinding | Expected | Actual |
| --- | --- | --- |
| `ctrl+d` | Half page down | ReSharper duplicate line |
| `ctrl+f` | Page down | Visual Studio find |
| `ctrl+o` | Previous jump position | File Open dialog |
| `ctrl+i` | Next jump position | Incremental search |

I use the `ReSharper 2.x or InelliJ IDEA` keybindings. I use two other environments with the same configuration. The only difference I see is that for the other two environments I use Visual Studio 2017 Professional.

I've no idea, what I'm doing wrong...! Do you have any idea? Please help me, because without this extension I'm unable to work! :-)

Thanks in advance!

**Comment by jaredpar** [comment] 2018-11-26 14:36
This is unfortunately a known issue that is hard to work around. The problem is how conflicting key detection works. VsVim looks at the set of available key bindings, determines which are in conflict and then puts those in this panel. When you remove a conflict though it removes the key binding. Visual Studio then helpfully sync's that removal to every instance of Visual Studio that you use. Hence when VsVim starts up on a new instance it sees no conflicting key bindings and leaves the panel empty. 

I've reported this problem to the Visual Studio team and they consider it "By Design". There isn't much for me to do here because I can't control the syncing' behavior. 

The options for working around this are:

- Go to Tools -> Options -> Environment -> Keybaord
- Hit "Reset"

That will essentually reset VS to the original mode at which point VsVim will see all of the conflicts again.

Dupe of #1658

**Closed by jaredpar** 2018-11-26 14:36 UTC

**Comment by FelixBoers** [comment] 2018-11-26 21:05
Thanks for your fast reply! 

Just resetting the keyboard settings wasn't enough, though. 
I'm not sure which step exactly solves my issue but after:

1. Removing everything (VisualStudi + Extensions and ReSharper)
2. Restarting
3. Installing Visual Studio
4. After logged in into Visual Studio, resetting all setting (Tools -> Import Export all Settings -> Reset all Settings)
5. Installing ReSharper and selecting keyboard layout
6. Installing VsVim

everything works properly! Thanks a lot, again!
