### ISSUE TITLE
Replace mode backspace doesn't work like Vim

### ISSUE THREAD

**Issue by jankner** [jaredpar/VsVim#1613] opened 2015-05-15 09:00 UTC
Backspace in replace mode should "undo" replacing characters rather than removing characters.

For example, entering replace mode, typing one character, then typing a backspace should have no effect. In VsVim it has the effect of removing one character.

**Comment by jaredpar** [comment] 2015-05-20 18:13
Thanks for reporting.  This looks like a duplicate of #653 though.

**Closed by jaredpar** 2015-05-20 18:13 UTC

**Comment by jankner** [comment] 2015-05-20 19:31
Oh, you're right. I don't know how i missed that.

**Comment by jaredpar** [comment] 2015-05-20 21:09
It can be easy to miss in the search.
