### ISSUE TITLE
VS2017 error IWpfTextView has not completed its layout on startup

### ISSUE THREAD

**Issue by daz10000** [jaredpar/VsVim#1946] opened 2017-04-26 15:14 UTC
Love VsVim.  Recently switched to VS2017 pro and it seems a little less happy. Seeing this error in the logs on startup.

 <description>System.InvalidOperationException: IWpfTextView has not completed its layout.&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.PerformLayout(ITextSnapshot newSnapshot, ITextSnapshot newVisualSnapshot, SnapshotPoint anchorPosition, Double verticalDistance, ViewRelativePosition relativeTo, Double effectiveViewportWidth, Double effectiveViewportHeight, Boolean preserveViewportTop, Nullable`1 cancel)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.DisplayTextLineContainingBufferPosition(SnapshotPoint bufferPosition, Double verticalDistance, ViewRelativePosition relativeTo, Nullable`1 viewportWidthOverride, Nullable`1 viewportHeightOverride)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.CaretElement.InnerEnsureVisible()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.DoActionThatShouldOnlyBeDoneAfterViewIsLoaded(Action action)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.CaretElement.EnsureVisible()&#x000D;&#x000A;   at Vim.Modes.Normal.NormalMode.OnEnter(ModeArgument arg)&#x000D;&#x000A;   at Vim.ModeMap.SwitchMode(ModeKind kind, ModeArgument arg)&#x000D;&#x000A;   at Vim.VimBuffer.SwitchMode(ModeKind modeKind, ModeArgument modeArgument)&#x000D;&#x000A;   at Vim.VimBuffer.Vim-IVimBuffer-SwitchMode(ModeKind kind, ModeArgument arg)&#x000D;&#x000A;   at &lt;StartupCode$Vim-Core&gt;.$Vim.runInit@312(IVimBuffer vimBuffer, ITextView textView, IVimBufferData vimBufferData, Unit unitVar0)&#x000D;&#x000A;   at &lt;StartupCode$Vim-Core&gt;.$Vim.SetupInitialMode@326-4.Invoke(TextViewLayoutChangedEventArgs _arg2)&#x000D;&#x000A;   at Microsoft.FSharp.Control.CommonExtensions.SubscribeToObservable@2102.System-IObserver`1-OnNext(T value)&#x000D;&#x000A;   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.h@788.Invoke(Object _arg1, TArgs args)&#x000D;&#x000A;   at &lt;StartupCode$Vim-Core&gt;.$Vim.SetupInitialMode@325-3.Invoke(Object sender, TextViewLayoutChangedEventArgs e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)</description>

**Comment by jaredpar** [comment] 2017-05-16 15:06
Thanks for reporting.  This looks like a dupe of #1904

**Closed by jaredpar** 2017-05-16 15:06 UTC
