### ISSUE TITLE
% only works over the {

### ISSUE THREAD

**Issue by pescuma** [jaredpar/VsVim#1715] opened 2015-12-09 01:39 UTC
I think it should find the nearest { in the line and then go to its match.

**Comment by jaredpar** [comment] 2015-12-10 07:00
Do you have some sample code that demonstrates this problem?

**Comment by pescuma** [comment] 2015-12-10 15:44
I'm sorry. I've just tested and it is working. I probably did something wrong in the other day, because this is the second issue that I created an is working.

**Comment by pescuma** [comment] 2015-12-10 17:31
Ops, spoke too soon. I was able to reproduce it in this code:

```
		public override void Name(List<object> parameter)
		{
			throw new NotImplementedException();
		}
```

   1. Move the cursor over `Name`
   1. `Shift-V` to go to visual line mode
   1. `j` to move down. The cursor will be in the char after `{`
   1. Press `%`. Nothing happens. (If you move to the beginning of the like it works)

**Comment by jaredpar** [comment] 2015-12-17 23:22
Thanks for clarifying.  I confirmed that is the behavior on gVim.  Will see what is going on with VsVim here.

**Comment by baldurk** [comment] 2016-01-03 19:03
FYI I have a local hack to fix this, you can replicate the behaviour also just by clicking on the line anywhere after the `{`, as that places the cursor on the character after the the `{`. I checked to see if the bug was fixed in the latest release and found this issue.

The hack is in MotionUtil.fs, in [MatchingTokenUtil](https://github.com/jaredpar/VsVim/blob/master/Src/VimCore/MotionUtil.fs#L699) it only searches strictly forward from column. I just added some code to effectly clamp it to the 'real' end of the line:

```diff
diff --git a/Src/VimCore/MotionUtil.fs b/Src/VimCore/MotionUtil.fs
index 889e48b..af2edbb 100644
--- a/Src/VimCore/MotionUtil.fs
+++ b/Src/VimCore/MotionUtil.fs
@@ -692,7 +692,11 @@ type MatchingTokenUtil() =

         let line = SnapshotPointUtil.GetContainingLine point
         let lineText = SnapshotLineUtil.GetText line
-        let column = point.Position - line.Start.Position
+        let column =
+            if point.Position = line.End.Position then
+                max 0 (line.End.Position - line.Start.Position - 1)
+            else
+                point.Position - line.Start.Position
         let found =
             match x.FindMatchingTokenKindCore lineText column with
             | None -> None
```

I have no idea if that's the right fix though, it just worked for me :).

**Comment by jaredpar** [comment] 2016-01-04 14:33
Hmm, was looking at the issue this morning and right now VsVim appears to be conforming to gVim behavior here (despite my previous experiment).  gVim only appears to respect `%` commands when the brace occurs after or on the caret.  It does not search before.  This behavior is also reflected in comments in the source code hence I believe it to be the correct behavior as is. 

Do you see the behavior you are expecting in gVim?

**Comment by jaredpar** [comment] 2016-01-04 14:37
Ah I seem to have figured it out.  The key here is the white space which occurs after the `{`.  If there is no white space then the bug description is correct: `%` should match the later bracket.  This is because the visual display is a bit deceptive here.  The caret is functionally on the last column of the line even though visually it is past it.  

If there is white space though then the `%` operation should not match.  The `%` motion never looks backwards for matching token, only current and forward on the same line.

**Comment by jaredpar** [comment] 2016-01-04 14:45
@baldurk yep, that's essentially the fix that is needed.

**Closed** 2016-01-09 21:49 UTC
Labels: Bug

**Comment by pescuma** [comment] 2016-08-16 12:44
@jaredpar Thanks!
