### ISSUE TITLE
:marks cmd doesn't list all global marks

### ISSUE THREAD

**Issue by cbates-** [jaredpar/VsVim#2393] opened 2018-10-18 17:31 UTC
If I set a mark in buffer A  (FileA.cs):
m-A
then list marks in buffer A:
:marks
I see something like:
mark    line   col   file/text
A           23      16  c:\work\test\FileA.cs

If I switch to buffer B and run the 'marks' command, 'A' is not displayed.

**Comment by ricksladkey** [comment] 2018-10-18 17:41
Thanks for taking the time to report a bug! The good news is that this issue is a duplicate of issue #1872 and has already been fixed in PR #2139.

**Closed by ricksladkey** 2018-10-18 17:41 UTC
