### ISSUE TITLE
multiple-lines are selected when I drag the mouse on the same line

### ISSUE THREAD

**Issue by JasonYang007** [jaredpar/VsVim#1682] opened 2015-10-24 18:39 UTC
Hi, I really appreciate for this wonderful Vim plugin. I am quite amazed by such a good compatibility with gVim editor. However, I found the following issues that are quite annoying in my daily job:
(1) When I drag the mouse to select a portion of text, multiple lines are automatically selected even though the mouse movement is on the same line.
(2) Vim's selection in command line mode is consistently inclusive, but VsVim doesn't look so. Below is an example with one line of sample text:  
     xyz.abc

When I double-click xyz:
(gVim) xyz is marked and the block cursor is at z. yank and paste results in xyz
(VsVim) xyz is marked and the block cursor is at the period. yank and paste results in xyz though.
--> block cursor is NOT inclusive

When I type vw at x, both gvim and VsVim show the block cursor at z, and yank catches xyz
--> block cursor is now inclusive.

**Comment by jaredpar** [comment] 2015-10-26 03:56
I believe the second issue is just a bug.  In general double click selection is handled by Visual Studio because it's *mostly* compatible with gVim.  This seems like a case where they differ and I need to handle it.  

For the first issue though I can't reproduce the problem.  In general selection is handled by Visual Studio (unless your vimrc has settings to dictate otherwise).  So selection should just be normal character wise selection.  Is there a specific case you can show me that I can look at?

**Comment by kellyelton** [comment] 2016-02-26 21:28
I think the first thing he mentioned is #1628

**Comment by ricksladkey** [comment] 2018-08-09 18:59
The first bug was fixed in PR #1747. The second bug only occurs with `:set selection=inclusive`.

**Comment by ricksladkey** [comment] 2018-08-16 15:05
I think this issue needs to stay open because the second bug is still present in VsVim.

**Closed** 2018-10-08 04:29 UTC
Labels: bug
