### ISSUE TITLE
Indenting in Visual Block mode only increases indentation

### ISSUE THREAD

**Issue by arijoon** [jaredpar/VsVim#1940] opened 2017-04-04 14:17 UTC
In visual block mode (Ctrl-Q) 

 - **Current Behavior**: pressing '>' or '<' will both add indentation (move right). 
 - **Expected behavior**:  Pressing '>' adds indentation and '<' removes indentation (modes left)

**Comment by sqlkoala** [comment] 2018-01-02 13:08
I checked the behavior and vsvim acts as described.
But there is visual line mode, where >  and < work as expected.
@arijoon is there a case where one has to use visual block?

**Comment by jaredpar** [comment] 2018-01-09 06:07
Looks like a dupe of #1453

**Closed by jaredpar** 2018-01-09 06:07 UTC
Labels: bug

**Comment by arijoon** [comment] 2018-01-11 12:17
@sqlkoala I don't exactly remember why I was doing this in visual block and not visual line, nevertheless it's best if the feature is always working as expected. (doubt this is a high priority item)
