### ISSUE TITLE
Show vimrc line numbers in error log file

### ISSUE THREAD

**Issue by philipmat** [jaredpar/VsVim#1586] opened 2015-03-26 19:31 UTC
When VimRc error reporting is turned on, would it be possible to show a line number with each of the errors being displayed in the log file? E.g.

```
13: Parse error
57: An error was encountered interpreting the expression
```

If not, would it be possible to show the line that caused the error?

**Comment by jaredpar** [comment] 2015-03-27 17:20
@philipmat it should be possible to add this information.

**Comment by jaredpar** [comment] 2018-01-09 06:30
Looks like a dupe of #1153

**Closed by jaredpar** 2018-01-09 06:30 UTC
Labels: bug
