### ISSUE TITLE
Using Ctrl+o in insert mode can't append after last character

### ISSUE THREAD

**Issue by pierremoreau** [jaredpar/VsVim#1566] opened 2015-02-23 15:33 UTC
If I use Ctrl+o,$ in insert mode to go to the end of current line and start appending text, the cursor will be placed before the last character rather than after.
Similarly, using Ctrl+o,l - still in insert mode - with the cursor before the last character, the cursor won't move to the character on its right.

**Comment by jaredpar** [comment] 2015-02-23 19:23
Thanks for taking the time to report this issue.

This is a dupe of #1462.  Going to use that as the primary to track this problem.

**Closed by jaredpar** 2015-02-23 19:23 UTC

**Comment by pierremoreau** [comment] 2015-02-23 19:39
Oh right, I completely forgot to check for existing bug reports... My bad!

**Comment by jaredpar** [comment] 2015-02-23 19:40
No problem.  I've gotten quite adept at searching for cryptic vim key commands in GitHub.  It's a skill ;)
