### ISSUE TITLE
'[ and `[ are reversed in the new release

### ISSUE THREAD

**Issue by cmaughan** [jaredpar/VsVim#2312] opened 2018-08-09 16:25 UTC
I just tried the latest installer.
Backtick is supposed to take you to the column of the paste, apostrophe the line, but it looks like they work in reverse......
http://vim.wikia.com/wiki/Using_marks

**Comment by ricksladkey** [comment] 2018-08-09 17:04
I cannot reproduce this. Here are my results with the head of master with the following buffer (where vertical bar represents the caret):

```
cat |dog bat
```

Type `dw`

```
cat |bat
```

Type: `P`:

```
cat dog| bat
```

Type: `'[`

```
|cat dog bat
```

Type: ``` `[```

```
cat |dog bat
```

**Comment by cmaughan** [comment] 2018-08-09 17:32
OK, I was confused by the behavior, but I think it is right: here's what I did.
VjjY to Select 2 rows.
p to paste

   Source Row 1(note tab before it)
   Source Row_2

   SourceRow_1
   SourceRow_2

`[ places me at the _beginning_ of SourceRow_1, before the tab.
'[ places me at the start of the word 'SourceRow_1'

I think this is actually correct.  The paste has started from the beginning of the line, but '[ is taking me to the first characters on the line.....

Sorry for the confusion.

**Comment by ricksladkey** [comment] 2018-08-09 17:40
@cmaughan Not a problem! The vim definition of "start of line" for the `'` command is "the first non-blank character" and the use case you described is indeed a little counter-intuitive at first blush.

If you agree that things are working correctly, then can close this issue if you feel the problem is solved.  Thanks!

**Comment by cmaughan** [comment] 2018-08-09 18:12
Yes, agreed a problem with my understanding :) And thanks for the info on '.  I could spend a lifetime and never learn all vim's quirks ;)  
By the way, I _love_ the marks visual display down the left side in Visual Studio.... Really nice!

**Comment by jaredpar** [comment] 2018-08-14 03:43
> By the way, I love the marks visual display down the left side in Visual Studio.... Really nice!

Yeah this is really nice.

**Closed** 2018-08-14 03:43 UTC
