### ISSUE TITLE
Introduce the setting `nrformat` for increment/decrement of "numbers"

### ISSUE THREAD

**Issue by MartinL0815** [jaredpar/VsVim#1986] opened 2017-08-17 12:13 UTC
Hi,

I recently needed to work more on hexadecimal numbers and stumbled about the problem, that VsVim does not increment hexadecimal numbers.

In VIM I never thought about it, since it worked out of the box. Then I read about the nrformat option/setting, which allows by default to in/decrement "octal" and "hex" numbers additional to decimal numbers.

Could you please check whether the in/decrement of numbers may be extended to support the defaults or to support a new ported setting equal to the VIM setting nrformat?

Best regards,

Martin

**Comment by ricksladkey** [comment] 2018-08-05 04:27
This is a dupe of issue #1765, because `nrformat` is already implemented and the `hex` setting is already supported, it just doesn't work in certain circumstances.

**Closed** 2018-08-08 03:29 UTC
Labels: feature request
