### ISSUE TITLE
Intermittent VS 2017 Hang

### ISSUE THREAD

**Issue by yokkey** [jaredpar/VsVim#2496] opened 2019-04-22 18:44 UTC
Hi, 
I'm experiencing occasional random hang of few seconds, whilst editing, when switching open files, when selecting text, on visual studio 2017. I've attached a stack trace of devenv.exe when it gets suspended. Observing this it is trying to settings which leads to accessing the registry. Wonder what could cause the thread to suspend (virus scanner?), and why vsvim should need to access settings so frequently. Thanks.
[stack.txt](https://github.com/jaredpar/VsVim/files/3104472/stack.txt)

**Comment by ricksladkey** [comment] 2019-04-23 02:57
I believe the settings access frequency has already been addressed in PR #2484.

Your situation might be different, but in my case symptoms like that have occurred when Visual Studio is running low on virtual memory. Because Visual Studio is 32-bit and limited to a 32-bit address space, the first symptom of excessive memory use or a memory leak is an increase in the frequency of garbage collection. In general Visual Studio with a commit size in excess of about 1.5 G will cause problems, which you can check with task manager.

If the problem is garbage collection, the stack trace is likely to report VsVim in the stack even though VsVim as a rule is not ill-behaved memory-wise. But it is also possible that when the heap subsystem is stressed, that VsVim exacerbates it in some way, such as creating a lot of small generation 0 allocations as a side effect of:

- Necessary consequences of implementing vim operations
- Some increased dependence on the heap due to the functional programming style
- Memory churn due to tracing

This last category would be possible to eliminate. But no matter how much memory tracing uses when there are no trace listeners, there is dramatically more memory allocated when the VsVim output pane is enabled, perhaps accidentally. So make sure that VsVim isn't doing that (Tools -> Options -> VsVim -> General -> Output Window -> False).

**Comment by jaredpar** [comment] 2019-04-23 05:02
Agree with @ricksladkey that this was fixed in #2484. This will be included in the next release. In the meantime though you can grab the latest build off of the Open VSIX gallery and it will have the fix.

http://vsixgallery.com/extension/VsVim.Microsoft.e214908b-0458-4ae2-a583-4310f29687c3/

**Closed by jaredpar** 2019-04-23 05:02 UTC

**Comment by TKumadaki** [comment] 2019-04-23 13:40
I thought that the gallery's VsVim would be automatically placed once it was merged.
It seems that VsVim in the gallery has not been updated since February.
and it seem not to be running CleanVsix.
Visual Studio sdk dll is included.
Is this intentional?
I am sorry if it was my mistake.

**Comment by ricksladkey** [comment] 2019-04-23 18:46
Thanks @TKumadaki. Create a new issue here: #2497.
