### ISSUE TITLE
Vi{ doesn't create a line selection, functions like vi{

### ISSUE THREAD

**Issue by ianwjhalliday** [jaredpar/VsVim#1000] opened 2012-11-27 21:43 UTC
Same with Va{

I'm seeing this in VS 2012 with VsVim 1.3.1.3

**Comment by Kantis** [comment] 2015-01-08 22:14
Attempted to replicate in VS2013, VsVim 1.6.0.3 and it seems to be working as intended now. Vi{ puts VsVim in Visual Line mode

**Comment by ianwjhalliday** [comment] 2015-01-08 22:34
I still see this issue in C++ in VS2013 with VsVim 1.7.1.1.

Also iB doesn't work correctly, it includes the braces, which only aB is supposed to do.

**Comment by Kantis** [comment] 2015-01-08 23:00
Just upgraded to 1.7.1.1. ViB and viB both creates a visual selection of the block, excluding braces.

![Example](http://i.imgur.com/TqqOkwJ.png)

**Comment by ianwjhalliday** [comment] 2015-01-09 00:16
It still selects the newlines and whitespace adjacent to the braces, and it
is not line mode selection if used with V rather than v.

E.g. >iB tabs the braces along with the contents.  It is only supposed to
tab the contents.  diB shouldn't collapse the braces to one line adjacent
to each other, but it does.

Try using it with a few verbs and then compare behavior with vim.

**Comment by Kantis** [comment] 2015-01-09 01:03
Ah ok. This has been fixed in master. https://github.com/jaredpar/VsVim/pull/1475

**Comment by ianwjhalliday** [comment] 2015-06-16 19:06
Thanks @Kantis!  I tried it out and it works!  However, I also tried Va{ and VaB and they still behave like va{ and vaB.  Since you took a crack at Vi{ do you think it will be quick and easy for ya to fix Va{?

**Comment by ricksladkey** [comment] 2018-08-08 19:38
The title of this issue is "Vi{ doesn't create a line selection, functions like vi{" but vim does not respect the difference between `vi{` and `Vi{` and neither does VsVim. Perhaps older versions of vim did not behave this way.

From vim `:help i{`:

> When used in Visual mode it is made characterwise.

If you want a linewise selection using `i{`, in either vim or VsVim, you must use, e.g., `vi{V`.

If you agree, @ianwjhalliday, this issue can be closed. If not, we need a specific repro that succeeds in vim but fails in VsVim.

**Closed** 2018-09-17 03:51 UTC
Labels: bug, check repro, motion, need more data
