### ISSUE TITLE
Exception when opening first solution

### ISSUE THREAD

**Issue by dwo77** [jaredpar/VsVim#2375] opened 2018-09-20 07:59 UTC
VS 2013. Just updated to VsVim 2.6.1203.

When I open the first solution, I get an exception message. Error text from ActivityLog.xml is:

> System.ComponentModel.Composition.CompositionException: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information. 1) Cannot compose part 'Vim.Vim' because a cycle exists in the dependencies between the exports being composed. To break this cycle, consider changing some imports from constructor to property injection. Element: Vim.Vim --> Vim.Vim Resulting in: Cannot get export 'Vim.Vim (ContractName="Vim.IVim")' from part 'Vim.Vim'. Element: Vim.Vim (ContractName="Vim.IVim") --> Vim.Vim Resulting in: Cannot set import 'Vim.VisualStudio.Implementation.Misc.FallbackKeyProcessorProvider..ctor (Parameter="vim", ContractName="Vim.IVim")' on part 'Vim.VisualStudio.Implementation.Misc.FallbackKeyProcessorProvider'. Element: Vim.VisualStudio.Implementation.Misc.FallbackKeyProcessorProvider..ctor (Parameter="vim", ContractName="Vim.IVim") --> Vim.VisualStudio.Implementation.Misc.FallbackKeyProcessorProvider Resulting in: Cannot get export 'Vim.VisualStudio.Implementation.Misc.FallbackKeyProcessorProvider (ContractName="Microsoft.VisualStudio.Text.Editor.IKeyProcessorProvider")' from part 'Vim.VisualStudio.Implementation.Misc.FallbackKeyProcessorProvider'. Element: Vim.VisualStudio.Implementation.Misc.FallbackKeyProcessorProvider (ContractName="Microsoft.VisualStudio.Text.Editor.IKeyProcessorProvider") --> Vim.VisualStudio.Implementation.Misc.FallbackKeyProcessorProvider at System.ComponentModel.Composition.Hosting.CompositionServices.GetExportedValueFromComposedPart(ImportEngine engine, ComposablePart part, ExportDefinition definition) at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportedValue(CatalogPart part, ExportDefinition export, Boolean isSharedPart) at System.ComponentModel.Composition.Hosting.CatalogExportProvider.CatalogExport.GetExportedValueCore() at System.ComponentModel.Composition.Primitives.Export.get_Value() at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export) at System.ComponentModel.Composition.ExportServices.<>c__DisplayClass11_0`2.<CreateStronglyTypedLazyOfTM>b__1() at System.Lazy`1.CreateValue() at System.Lazy`1.LazyInitValue() at System.Lazy`1.get_Value() at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)

VsVim works, and when I open another project, no exception occurs.

**Comment by jaredpar** [comment] 2018-09-20 21:42
This looks like a duplicate of #2249. I'm looking into this.

**Closed by jaredpar** 2018-09-20 21:42 UTC
