### ISSUE TITLE
Basic jk support for navigating in solution explorer

### ISSUE THREAD

**Issue by prabirshrestha** [jaredpar/VsVim#1549] opened 2015-01-16 21:41 UTC
This might be out of scope but would be awesome to have basic jk navigation support for solution explorer.

**Comment by v-yadli** [comment] 2015-01-17 06:37
Cool, how about showing/hiding solution explorer with :NerdTreeToggle ? :-)

**Comment by jaredpar** [comment] 2015-01-17 17:31
Thank you for filing this issue.  It is a duplicate of #1461.

**Closed by jaredpar** 2015-01-17 17:31 UTC
