### ISSUE TITLE
unnamed clipboard not working in Win10

### ISSUE THREAD

**Issue by hyh** [jaredpar/VsVim#1647] opened 2015-07-30 20:19 UTC
Hi, I'm using Win10 and VS2015 and I have ```set clipboard=unnamed``` in my vimrc.
VS constantly reports plugin exception on commands with copy (like yy or dd).
Here's the detail extracted from ActivityLog.xml:
```
  <entry>
    <record>1085</record>
    <time>2015/07/30 20:02:48.022</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))&#x000D;&#x000A;   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)&#x000D;&#x000A;   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)&#x000D;&#x000A;   at System.Windows.Clipboard.SetDataInternal(String format, Object data)&#x000D;&#x000A;   at System.Windows.Clipboard.SetText(String text, TextDataFormat format)&#x000D;&#x000A;   at System.Windows.Clipboard.SetText(String text)&#x000D;&#x000A;   at Vim.UI.Wpf.Implementation.Misc.ClipboardDevice.&lt;&gt;c__DisplayClass4.&lt;SetText&gt;b__3()&#x000D;&#x000A;   at Vim.UI.Wpf.Implementation.Misc.ClipboardDevice.TryAccessClipboard(Action action, Int32 retryCount, Int32 pauseMilliseconds)</description>
  </entry>
```

**Comment by jaredpar** [comment] 2015-08-01 15:27
@jasonmalinowski have you seen this on Windows 10?

**Comment by jasonmalinowski** [comment] 2015-08-03 18:29
I just tried to reproduce this on the released Windows 10 build and it worked fine for me.

**Comment by fredizzimo** [comment] 2015-08-05 19:41
I just happened to see that there apparently are big problems with ctrl-c in windows 10 see here for example https://twitter.com/tomwarren/status/626428691703275520. So that could be related, and maybe it's worth waiting until that's fixed before looking into the issue.

**Comment by jaredpar** [comment] 2015-08-05 21:33
Unfortunately this is an issue that I can't really control.  The clipboard is controlled by Windows and if it gets into a bad state, which apparently it can, then it can't be fixed by VsVim.  The code in question knows the clipboard is dangerous, wraps it in a `try / catch` and reports the issue to Visual Studio.  I can't stop reporting the problem because it would cause copy / paste to silently fail.

**Closed by jaredpar** 2015-08-05 21:33 UTC
Labels: Need More Data
