### ISSUE TITLE
Pasting clipboard into incremental search does not work

### ISSUE THREAD

**Issue by bbondy** [jaredpar/VsVim#1050] opened 2013-02-21 14:09 UTC
1. Copy some text.
2. Switch to Visual Studio and Type the '/' char to start an incremental search
3. Type Ctrl + V to paste the clipboard contents

Actual results:
Clipboard text gets pasted to the document you are editing

Expected results:
Pasted clipboard goes to the incremental search box.

It's a common use case for me. I copy some text form a code review web page, and then try to paste it into the incremental search box.

**Comment by jaredpar** [comment] 2018-01-01 18:08
Dupe of #623

**Closed by jaredpar** 2018-01-01 18:08 UTC
Labels: check repro, feature request
