### ISSUE TITLE
CTRL+A (and CTRL+X) issue with floating-point numbers

### ISSUE THREAD

**Issue by farzadmf** [jaredpar/VsVim#1869] opened 2016-11-28 03:58 UTC
I noticed something: if I have a value like: `0.03`, and I move the cursor on the decimal part (`03`) and press `CTRL+A` (or `CTRL+X`) to increment (or decrement) the value, it will ignore the leading zero and convert the number to `0.4` (or `0.2`)
I compared with vim, and the functionality in vim is as expected (it changes the number to `0.04` and `0.02`)

**Comment by jaredpar** [comment] 2016-12-04 04:58
Thanks for taking the time to report this issue.  Looks like it's a duplicate of #876.  Will let that be the primary tracker.

**Closed by jaredpar** 2016-12-04 04:58 UTC
