### ISSUE TITLE
Exception yanking/deleting

### ISSUE THREAD

**Issue by cbates-** [jaredpar/VsVim#2080] opened 2018-02-14 16:21 UTC
VS 2015 Pro, update 3.
VsVim 2.5.0.0

I am seeing this error (copied below, from ActivityLog.xml)  more and more, typically when using commands such as _yiw_ , _diw_, _d2d_, etc.

Not every invocation of those commands, but often enough to be noticeable.
I'll try to pay attention to what I was doing immediately prior to trying to yank/delete, to see if  there is a consistent precursor to the error.

<entry>
    <record>620</record>
    <time>2018/02/14 15:47:35.762</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>

    <description>System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))&#x000D;&#x000A;   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)&#x000D;&#x000A;   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)&#x000D;&#x000A;   at System.Windows.Clipboard.SetDataInternal(String format, Object data)&#x000D;&#x000A;   at System.Windows.Clipboard.SetText(String text, TextDataFormat format)&#x000D;&#x000A;   at System.Windows.Clipboard.SetText(String text)&#x000D;&#x000A;   at Vim.UI.Wpf.Implementation.Misc.ClipboardDevice.&lt;&gt;c__DisplayClass4_0.&lt;SetText&gt;b__0()&#x000D;&#x000A;   at Vim.UI.Wpf.Implementation.Misc.ClipboardDevice.TryAccessClipboard(Action action, Int32 retryCount, Int32 pauseMilliseconds)</description>
  </entry>

**Comment by jaredpar** [comment] 2018-02-20 18:31
Thanks for reporting. Closing as a dupe of #2067.

**Closed by jaredpar** 2018-02-20 18:31 UTC
