### ISSUE TITLE
Is possible to list marks when pressing ' key?

### ISSUE THREAD

**Issue by brunocasarotti** [jaredpar/VsVim#2083] opened 2018-03-09 15:50 UTC
I was looking for somehow list marks in Vim when I found [this ](https://vi.stackexchange.com/questions/8451/is-it-possible-to-have-vim-show-the-list-of-available-marks-when-using-marks)on SO. I created a .vimrc file in my %USERPROFILE% folder with the following functions as described on the link above.

""""""""""""""""""""""""""""
" Ranger style marks command
"
""""""""""""""""""""""""""""
function! Marks()
    marks
    echo('Mark: ')

    " getchar() - prompts user for a single character and returns the chars
    " ascii representation
    " nr2char() - converts ASCII `NUMBER TO CHAR'

    let s:mark = nr2char(getchar())
    " remove the `press any key prompt'
    redraw

    " build a string which uses the `normal' command plus the var holding the
    " mark - then eval it.
    execute "normal! '" . s:mark
endfunction

nnoremap ' :call Marks()<CR>

So when I press ' I should get a list with all marks right?
Seems like some functionality isn't supported by VsVim as I get the following output:
:call to function Marks not supported

I am not a Vim guru by the way. Does anyone knows if it is possible to get this list? How?

**Comment by cbates-** [comment] 2018-03-09 17:01
Does 
`:marks`
note do what you are looking for?
![image](https://user-images.githubusercontent.com/1412601/37219467-7d1ac1bc-2391-11e8-9933-236e76fb7fa5.png)
Note that there is a problem with global marks ('C' in the image) -- they don't display if they are not in the current buffer.

**Comment by brunocasarotti** [comment] 2018-03-09 17:31
No, it isn't. What I am really looking for is a way to mix it with the command `'` so when I press it I can at the same time know those marks and press the corresponding key.
Imagine that you press `'` and that list is shown, so I can look at the list and press the key that corresponds to the desired mark without the need to write `:marks`

**Comment by ricksladkey** [comment] 2018-06-08 06:08
I think this is a effectively a duplicate of issue #574.

**Closed** 2018-07-12 01:02 UTC
