### ISSUE TITLE
force new undo group, works in Vim but no in VsVim

### ISSUE THREAD

**Issue by tldrlol** [jaredpar/VsVim#1661] opened 2015-08-20 17:30 UTC
I have in my `_vimrc` the following lines (which allow to undo c-w/u done from insert mode):

`" force c-u, c-w to start a new undo group`
`inoremap <c-u> <c-g>u<c-u>`
`inoremap <c-w> <c-g>u<c-w>`

It works flawlessly in Vim, but not in VsVim, where it inserts blue `^G`.

At the moment I'm looking for a decent workaround so that this only affects Vim and not VsVim. Any suggestions?

**Comment by jaredpar** [comment] 2015-08-21 05:45
Undo groups are not currently a supported feature for insert mode in VsVim.  I have a couple of issues tied to implementing them but I don't think it will get done anytime soon.  

Short term it's possible to separate the Vim and VsVim logic by having separate RC files:

- .vsvimrc: VsVim related settings
- .vimrc: Vim related settings

VsVim will always prefer `_vsvimrc` or `.vsvimrc` over normal vim RC files.

**Comment by jaredpar** [comment] 2018-01-12 04:20
Looks like this is a dupe of #757

**Closed by jaredpar** 2018-01-12 04:20 UTC
