### ISSUE TITLE
Double-clicking a word puts the caret outside the visual block, and then gp command "overwrites" one more character.

### ISSUE THREAD

**Issue by v-yadli** [jaredpar/VsVim#1858] opened 2016-11-03 04:09 UTC
Repro:
Given the following content in the buffer:
```
foo
bar baz
```

1. Yank 'foo' into register
2. Double click 'bar' with mouse
3. Issue command `gp`

Expecting (gVim7.4):
![issue-gvim](https://cloud.githubusercontent.com/assets/1008466/19955598/b984a048-a1bd-11e6-9ca8-681d3cd4dd33.gif)
1. After double-click, 'bar' is inclusively selected, and caret is placed at `r` of `bar`
2. gp overwrites `bar` with `foo`

Actual (VS2015+VsVim):
![issue-vsvim](https://cloud.githubusercontent.com/assets/1008466/19955602/bec774c2-a1bd-11e6-951e-70441e71f440.gif)
1. After double-click, 'bar' is inclusively selected, and caret is placed at ` ` after `bar`
2. gp overwrites `bar_` with `foo`, with the space after `bar` overwritten.

I believe this is related to the inclusive/exclusive selection mismatch between VS and Vim. Digging around the code I discovered related stuff in `SelectionChangeTracker.fs` where selection update is translated into mode switch. I tried to reposition the caret one step back (so that it falls into the selection) but it is not always working.. Double-clicking a word has different behavior when the click happens at different position: the caret may be positioned at the beginning of the word (which seems to be 'triggered again' somewhere after the initial selection update) or after the end of the selection.

**Comment by jaredpar** [comment] 2016-11-14 01:02
Thanks for reporting.  This looks like a dupe of the caret double click issues in the more recent releases.  This should all be fixed now with #1829.  Hopefullly be releasing again in the next week ro so.

**Closed by jaredpar** 2016-11-14 01:02 UTC
