### ISSUE TITLE
Disable vim command can get in a bad state

### ISSUE THREAD

**Issue by sgraup** [jaredpar/VsVim#1952] opened 2017-05-09 17:40 UTC
I've noticed that if I jump the gun on my build and hit ctrl+shift+F12 before I have errors in my incredibuild window, vim will toggle to disabled. Once there are errors in the window I can no longer enable vim since the incredibuild.NextError is eating the command. I assume this would also be the case if I was not using incredibuild since ctrl+shift+f12 is the default bind for View.NextError. 

Can I change the enable/disable mapping for vsvim?

**Comment by jaredpar** [comment] 2018-01-13 22:34
Closing as a dupe of #1685. Using that bug to track making this an official command with global scope. Will eliminate issues like this.

**Closed by jaredpar** 2018-01-13 22:34 UTC
