### ISSUE TITLE
count followed by go to next or previous matching character in line "<n>;" "<n>," don't seem to work.

### ISSUE THREAD

**Issue by chaitanyagurrapu** [jaredpar/VsVim#1978] opened 2017-08-02 00:53 UTC
In gvim lets say I have the following text and my cursor is at the beginning of the line on the 'c' character

    cat mat rat sat fat tat

pressing "fa" takes me to the "a" character in "cat". Subsequently pressing "2;" takes me to the "a" in "rat". Or "3;" would take me to the "a" in "sat" and then, if I press "2," it takes me back to the "a" in "mat"

The same behavior doesn't seem to be happening in vsvim. It always goes to the next/previous character occurrence in the line. In other words it is doing the ";", "," functionality, but not taking into account the count that comes before it.

**Comment by jaredpar** [comment] 2017-08-02 23:07
Interesting. Didn't know about that behavior.

**Comment by ricksladkey** [comment] 2018-05-13 04:08
I cannot reproduce this bug in VsVim 2.5.0.0 or on master. In the code base, both `f` and `;` are handled by the same `CharSearchCore c count kind direction`.

**Comment by chaitanyagurrapu** [comment] 2018-05-14 00:30
Hmm... I can't seem to reproduce it either.  I wonder if it was a clash with another tool in a  previous set up or just a figment of my deranged imagination.

**Comment by ricksladkey** [comment] 2018-12-20 05:50
Closing this as no longer reproducible.

**Closed by ricksladkey** 2018-12-20 05:50 UTC
Labels: bug
