### ISSUE TITLE
VsVim causes exception on Visual Studio Loading

### ISSUE THREAD

**Issue by DJMcMayhem** [jaredpar/VsVim#1699] opened 2015-11-12 17:12 UTC
When I opened VS this morning, I received this error:

    An exception has been encountered. This may be caused by an extenstion. You can get more information by examining the file C:\Users\jmhjr\AppData\Roaming\Microsoft\Visual Studio\12.0\ActivityLog.xml

In that file, I have this error repeated several times:

      <entry>
        <record>319</record>
        <time>2015/11/12 17:01:53.162</time>
        <type>Error</type>
        <source>Editor or Editor Extension</source>
        <description>System.ArgumentException: Illegal characters in path.&#x000D;&#x000A;   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)&#x000D;&#x000A;   at System.IO.Path.IsPathRooted(String path)&#x000D;&#x000A;   at Vim.SystemUtil.EnsureRooted(String currentDirectory, String text)&#x000D;&#x000A;   at Vim.SystemUtil.ResolveVimPath(String currentDirectory, String text)&#x000D;&#x000A;   at Vim.Interpreter.VimInterpreter.RunWrite[a,b](a lineRange, Boolean hasBang, FSharpList`1 fileOptionList, FSharpOption`1 filePath)&#x000D;&#x000A;   at Vim.Interpreter.VimInterpreter.RunScript(String[] lines)&#x000D;&#x000A;   at Vim.Interpreter.VimInterpreter.Vim-Interpreter-IVimInterpreter-RunScript(String[] lines)&#x000D;&#x000A;   at Vim.Vim.LoadVimRcCore()&#x000D;&#x000A;   at Vim.Vim.LoadVimRc()&#x000D;&#x000A;   at Vim.Vim.MaybeLoadVimRc()&#x000D;&#x000A;   at Vim.Vim.GetWindowSettingsForNewBuffer()&#x000D;&#x000A;   at Vim.Vim.TryGetOrCreateVimBufferForHost(ITextView textView, IVimBuffer&amp; vimBuffer)&#x000D;&#x000A;   at Vim.Vim.Vim-IVim-TryGetOrCreateVimBufferForHost(ITextView textView, IVimBuffer&amp; vimBuffer)&#x000D;&#x000A;   at Vim.VisualStudio.Implementation.Misc.VsVimKeyProcessorProvider.Microsoft.VisualStudio.Text.Editor.IKeyProcessorProvider.GetAssociatedProcessor(IWpfTextView wpfTextView)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.InputController.&lt;UpdateKeyProcessors&gt;b__2(IKeyProcessorProvider p)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)</description>
      </entry>

I uninstalled and reinstalled VsVim, but I am still getting this error, which causes vsvim to be unusable.

**Comment by jaredpar** [comment] 2015-11-14 16:44
Sorry about this. 

Based on the stack it looks like VsVim is having a problem loading your vimrc file. In particular a ':write' command. In the short term u should be able to work around this by removing that line. Or just add a an empty .vsvimrc file in your home directory. 

I'll get a fix submitted for this over the weekend.

**Comment by DJMcMayhem** [comment] 2015-11-17 17:11
Strange. It definitely has something to do with my vimrc, but I can't figure out what. If I comment out every line, it still crashes, but If I remove every line it is fine. And then I can add a couple of lines back into the vimrc, but if I add all of them it still crashes. I have not been able to figure out a pattern for what it crashes on or not, but I'll keep experimenting with it.

**Comment by idealist1508** [comment] 2015-11-20 07:30
If you wish i can try your config. Please upload it as a file, not just a text. Mayby there something wrong with newlines or some other issue with an encoding.

**Comment by jaredpar** [comment] 2015-11-20 16:09
I've submitted a fix for this.  But I'm still very interested in the vimrc file you have that was able to hit this.  I want to make sure there are no other hidden issues that I'm missing here.  If you could provide it that would be great.

**Comment by DJMcMayhem** [comment] 2015-11-23 17:31
Alright, sure. Here is my .vimrc in all of it's messiness. I'll try running it with that fix and see if it works.

[vimrc.txt](https://github.com/jaredpar/VsVim/files/41837/vimrc.txt)

**Comment by jaredpar** [comment] 2015-11-28 04:28
@DJMcMayhem thanks for posting. I see what line is causing the problem.  Going to further guard against that type of error.

**Comment by DJMcMayhem** [comment] 2015-11-28 08:49
@jaredpar Well, now you've got me all curious. What was the problem?

**Comment by jaredpar** [comment] 2015-11-28 16:57
@DJMcMayhem this line

```
:w'
```

The `'` character isn't a legal path character.

**Closed** 2015-11-28 17:20 UTC

**Comment by wongjiahau** [comment] 2017-09-05 00:58
I also face the same problem. 
## Steps to reproduce 
1. Shutdown Visual Studio 2017
2. Open Visual Studio 
3. Open any text file
4. Press 'dd' (which stands for delete a line)
5. Then the exception will be thrown after a few seconds of hanging

However, I still can use VsVim after this without any problem. Just that I found that a bit annoying whenever I just started my Visual Studio.
