### ISSUE TITLE
Shift + End selects remaining line excluding the last charecter

### ISSUE THREAD

**Issue by svarogg** [jaredpar/VsVim#1802] opened 2016-07-02 15:28 UTC
Very simple to reproduce:
1. Press i to enter insert mode
2. Enter Some Text
3. Press esc to exit insert mode
4. Go to the middle of the line
5. Press Shift + End

Expected result: VsVim goes to visual mode, and selects all the characters starting from cursor.
![expected](https://cloud.githubusercontent.com/assets/2129610/16541076/629d9dc6-4082-11e6-9e65-f84aa1dda19e.PNG)
Actual result: VsVim goes to visual mode, and selects all the characters starting from cursor, excluding the last character
![actual](https://cloud.githubusercontent.com/assets/2129610/16541077/62a1f330-4082-11e6-96ac-833c075c55a8.PNG)

This is not consistent with how Shift+Home works, and it is not consistent with what would happen if you skipped step 3 and stay in insert mode.
And, I believe all would agree with me, that this is not what a user would expect.

Edit: I did a bit more digging, and got a related buggy scenario:
1. Press i to enter insert mode
2. Enter Some Text
3. Press esc to exit insert mode
4. Go to the middle of the line
5. Press v to enter visual mode
6. Press End

Same thing happens - all but the last character is selected, while if you do the same in original vim  all characters would (I tested with cygwin default vim package).

**Comment by jaredpar** [comment] 2016-07-06 03:29
Thanks for taking the time to report this issue.  I believe I know the problem here.  Which version of VsVim are you on?

**Comment by svarogg** [comment] 2016-07-06 06:29
I'm on v2.1.1.0

**Comment by jaredpar** [comment] 2016-07-06 15:04
Thanks for confirming.  This looks like another duplicate of the EOL issue with selection in the 2.1 releases.  The 2.1.1 release fixed a number of the problems but left a few others.  Will look at this.

**Comment by jaredpar** [comment] 2016-12-04 04:23
Confirmed this was fixed with the other selection issues in the most recent source.

**Closed by jaredpar** 2016-12-04 04:23 UTC
Labels: Bug
