### ISSUE TITLE
Use % to move between matchpairs of <> (ala HTML, XML)

### ISSUE THREAD

**Issue by jpolfer** [jaredpar/VsVim#1556] opened 2015-02-05 20:49 UTC
I was using vim 7.4 and I noticed they supported using % to move between matchpairs of < and > in HTML files.

Is there a way to add this feature to VsVim?  It would be helpful when working with HTML and XML.

**Comment by jnothstine** [comment] 2015-02-05 21:00
This is a duplicate of #1255

**Comment by jaredpar** [comment] 2015-02-06 19:47
Thanks for taking the time to report this issue.  

As @jnothstine reported though this is a duplicate of #1255, going to let that be the primary tracker.

**Closed by jaredpar** 2015-02-06 19:47 UTC
