### ISSUE TITLE
Resharper Structural Search&Replace pattern editor exception.

### ISSUE THREAD

**Issue by friedroman** [jaredpar/VsVim#1600] opened 2015-05-01 23:51 UTC
When VsVim is enabled and you go to 'Resharper/Options/Code Inspections/Custom Patterns/Add Pattern' Visual Studio exception dialog pops up, but you still get to the pattern editor and VsVim is usable in its text editors (which I found extremely cool). Though after you cancel or confirm the pattern dialog VS becomes unresponsive and it appears as if there is some invisible modal dialog sitting somewhere.

If I disable VsVim with Ctrl+Shift+F12 everything works fine.

Exception entry in ActivityLog.xml:
```xml
<entry>
    <record>961</record>
    <time>2015/05/01 23:17:28.440</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.InvalidOperationException: IWpfTextView has not completed its layout.&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.PerformLayout(ITextSnapshot newSnapshot, ITextSnapshot newVisualSnapshot, SnapshotPoint anchorPosition, Double verticalDistance, ViewRelativePosition relativeTo, Double effectiveViewportWidth, Double effectiveViewportHeight, Boolean preserveViewportTop)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.DisplayTextLineContainingBufferPosition(SnapshotPoint bufferPosition, Double verticalDistance, ViewRelativePosition relativeTo, Nullable`1 viewportWidthOverride, Nullable`1 viewportHeightOverride)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.CaretElement.InnerEnsureVisible()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.DoActionThatShouldOnlyBeDoneAfterViewIsLoaded(Action action)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.CaretElement.EnsureVisible()&#x000D;&#x000A;   at Vim.Modes.Normal.NormalMode.OnEnter(ModeArgument arg)&#x000D;&#x000A;   at Vim.ModeMap.SwitchMode(ModeKind kind, ModeArgument arg)&#x000D;&#x000A;   at Vim.VimBuffer.SwitchMode(ModeKind modeKind, ModeArgument modeArgument)&#x000D;&#x000A;   at Vim.VimBuffer.Vim-IVimBuffer-SwitchMode(ModeKind kind, ModeArgument arg)&#x000D;&#x000A;   at &lt;StartupCode$Vim-Core&gt;.$Vim.runInit@283(IVimBuffer vimBuffer, ITextView textView, IVimBufferData vimBufferData, Unit unitVar0)&#x000D;&#x000A;   at &lt;StartupCode$Vim-Core&gt;.$Vim.SetupInitialMode@297-4.Invoke(TextViewLayoutChangedEventArgs _arg2)&#x000D;&#x000A;   at Microsoft.FSharp.Control.CommonExtensions.SubscribeToObservable@1777.OnNext(T value)&#x000D;&#x000A;   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.h@744.Invoke(Object _arg1, TArgs args)&#x000D;&#x000A;   at &lt;StartupCode$Vim-Core&gt;.$Vim.SetupInitialMode@296-3.Invoke(Object sender, TextViewLayoutChangedEventArgs e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)</description>
  </entry>
```
VsVim   1.8.0.0
JetBrains ReSharper Platform 6 Build 6.0.20141219.120158 on 2014-12-19 12:56:02Z
JetBrains ReSharper 9.0 Update 1 Build 9.0.20141219.130142 on 2014-12-19 13:12:31Z

Application Packages:
CitizenMatt PreviewTab build 1.1.4 on 2015-04-27 00:14:54Z.
JetBrains Fake VisualStudio VsPackageAssembly build 12.0.0.0 on 2015-04-27 00:15:14Z.
JetBrains Platform Core Ide build 6.0.20141219.120158 on 2014-12-19 12:56:02Z.
JetBrains Platform Core Shell build 6.0.20141219.120162 on 2014-12-19 12:53:09Z.
JetBrains Platform Core Text build 6.0.20141219.120158 on 2014-12-19 12:56:02Z.
JetBrains Platform Installer build 6.0.20141219.120158 on 2014-12-19 12:56:02Z.

Microsoft Visual Studio Ultimate 2013
Version 12.0.31101.00 Update 4
Microsoft .NET Framework
Version 4.5.51650

Code alignment   12
HideMenu   1.0
NCrunch

**Comment by jaredpar** [comment] 2015-05-02 23:05
Thanks for reporting.  I will take a look at that.

At a glance it looks like the root issue is that asking a caret about it's visibility can throw an exception.  That's ... odd but I need to guard against that.

**Comment by jaredpar** [comment] 2015-12-24 23:58
I just checked and this no longer reproduces in R# 10.2.  

The odd part is this code path is already specifically guarded against this problem.  I can't really add any extra guards unless I can see this reproducing live to figure out why it's being bypassed.  

Closing for now.  Please ping if this starts showing up again.

**Closed by jaredpar** 2015-12-24 23:58 UTC
Labels: Bug, Resharper
