### ISSUE TITLE
Page Up/Page Down much slower in 2.6 than 2.5

### ISSUE THREAD

**Issue by sid-6581** [jaredpar/VsVim#2407] opened 2018-11-01 19:25 UTC
Whenever I press page up or page down in version 2.6, it seems like it takes a full second or so before anything happens. I downgraded to 2.5, and the issue went away completely -- the editor is responsive again.

**Comment by sid-6581** [comment] 2018-11-02 14:02
I have the same issue with `<C-u>` and `<C-d>` in 2.5 and 2.6. `<PageUp>`/`<PageDown>` are even slower in 2.6 than `<C-u>`/`<C-d>` is in 2.5/2.6, which I guess makes sense since it's scrolling more lines. I've avoided those motions for that reason, but I can't avoid both those and  page up/down, because I can't be scrolling line by line through the code all the time.

It's hard to time this exactly, but `<C-u>`/`<C-d>` seem to take over 0.5s in both 2.5 and 2.6, and `<PageUp>`/`<PageDown>` seem to take over one second in 2.6 but is fine in 2.5. I tried upgrading back up to 2.6 and turning off hardware acceleration, but that didn't make a difference, it was still as slow as before.

2.6 for me is unfortunately not usable as things stand right now, so I'm forced to revert to 2.5. I'm assuming that this is not a bug that affects everyone?

**Comment by ricksladkey** [comment] 2018-11-02 16:11
My by-page scrolling is basically instant and so I don't experience the problem. And, yes, I too would find it incredibly annoying and nearly unusable if it were pathologically slow as you are reporting.

I did a little research and found [this quote](https://social.msdn.microsoft.com/Forums/en-US/af95c24b-cf78-4f89-9411-43e695420c7d/vs2010-slow-scrolling?forum=vseditor) from the program manager of the Visual Studio editor at the time:

> ScrollViewportVerticallyByLines will scroll one line at a time until all of the lines have been scrolled, which will cause layouts proportional to the number of lines.

If that is true, we certainly don't need it to do that for our purposes (do multiple layers per call) and so we might be able to get the desired effect using a different API that doesn't have this flaw.

Also, if it is true, then there might be a whole spectrum of symptoms depending on the speed of the machine, graphics card, etc. in which the vast majority of users are "a little bit slow" but not "annoyingly so". In other words, it might not be noticeable for everybody, but we might be slowing everybody at least a little.

In any case, I am now confident that this issue is a duplicate of #1633 because `<C-u>`/`<C-d>` is also slow for you, even for VsVim 2.5.0. As a result, I'll close this issue and leave that one open.

**Closed by ricksladkey** 2018-11-02 16:11 UTC

**Comment by ricksladkey** [comment] 2018-11-03 21:45
@sid-6581 If you get a chance, I have a question for your over in the original issue #1633.
