### ISSUE TITLE
Add support to g; and g, to go to previous/next edit place.

### ISSUE THREAD

**Issue by lorry-lee** [jaredpar/VsVim#1889] opened 2016-12-21 15:29 UTC
In vim you can use g; and g, to go to previous/next edited place, to navigate between the history of changes in current buffer.

I'm wondering is it possible to do the same in vsvim.

**Comment by jaredpar** [comment] 2016-12-26 19:09
Thanks for reporting.  This is a duplicate of #750.  Going to use that as the primary.

**Closed by jaredpar** 2016-12-26 19:09 UTC
