### ISSUE TITLE
Hitting enter skips over VIM text bar if highlighting non-whitespace

### ISSUE THREAD

**Issue by Thurge** [jaredpar/VsVim#1919] opened 2017-02-16 16:49 UTC
When attempting to type in VIM text bar (:w) if the cursor is highlighting non blank text, when I hit enter, my vim command is not accepted (in this case, :w is still shown in the text bar) and I end up adding a new line in my file!! super annoying.

**Comment by farzadmf** [comment] 2017-02-16 19:04
I think it's the same problem I had #1840, where, on of my computers, this was happening... The problem is that the focus isn't transferred to the command bar. If you use the mouse and click on the command bar, then you can run the command by pressing `ENTER`

**Comment by jaredpar** [comment] 2018-01-13 22:18
Yeah this looks like a dupe of #1840

**Closed by jaredpar** 2018-01-13 22:18 UTC
