### ISSUE TITLE
Ctrl-T is missing from the conflict key list

### ISSUE THREAD

**Issue by hollasch** [jaredpar/VsVim#2111] opened 2018-05-03 21:56 UTC
Issues #251 and #968 lead me to believe that <Ctrl-T> in insert mode is supposed to be working. However, this command is missing from the VsVim Keyboard options (<Ctrl-D> is present).

**Comment by sqlkoala** [comment] 2018-05-04 18:57
Hi,
the command is implemented in Vsvim. You can check with this mapping:
`:inoremap <Tab> <C-t>`
After that Tab will do the Ctrl-t function.
The problem is that VsVim is not properly set up to handle/capture Ctrl-t in your case.

What happens if you press Ctrl-t?

**Comment by hollasch** [comment] 2018-05-04 19:50
Currently Ctrl-T launches VisualStudio's symbol search dialog.

**Comment by ricksladkey** [comment] 2018-05-04 21:38
My guess is that, for whatever reason, VsVim failed to detect that the text editor has assigned bindings for `Ctrl+T` and, as a result, failed to remove them.

Whenever you *know* that VsVim supports a key, but the key doesn't behave appropriately, your first line of defense is to go to Tools -> Options -> Environment -> Keyboard, click on "Press shortcut keys:" and type the key.  Then look at the "Shortcut currently used by:" list. You don't necessarily need to remove all the bindings, but anything Global or Text Editor binding will prevent VsVim from seeing the key.

Type the name of the command in the binding in "Show commands containing:", select the "Shortcuts for selected binding" that uses the offending key and then click Remove.  Repeat until no bindings in Global or Text Editor has any binding for the the key.

**Comment by ricksladkey** [comment] 2018-05-04 21:42
Forgot I wrote this in more detail several years ago:

https://github.com/jaredpar/VsVim/wiki/Troubleshooting-the-Keyboard

**Comment by ricksladkey** [comment] 2018-05-05 00:32
Agreed, that's a bug.

**Comment by ricksladkey** [comment] 2018-06-11 23:57
Insert mode was building its key bindings on demand. When the conflict resolution dialog asked for its bindings, it didn't see fit to build them. Fixed in PR #2197.

**Closed** 2018-06-14 10:54 UTC
