### ISSUE TITLE
"." gets messed up when Resharper is turned on

### ISSUE THREAD

**Issue by FarmerBob** [jaredpar/VsVim#1543] opened 2015-01-12 08:26 UTC
Repro:

var a = 1;
var b = 2;

With cursor on the first line, type A[BACKSPACE]ToString();[ESC]
Move cursor to the second line, type "." to repeat.

I get:
            var b = 2.To_ToStrin;
If I do it inside a @"" quoted string, this doesn't happen, so it must be an intellisense.  However, this happens even if I type out each letter without using intellisense.

I suspended Resharper and then found that his no longer happens.  Resharper 8.2, Visual Studio 2013 Update 2.

**Comment by jaredpar** [comment] 2015-01-12 15:51
Thats for the information.  I will look into that.

**Comment by jnothstine** [comment] 2015-01-12 15:56
This looks like it may be a duplicate of #1353

**Comment by jaredpar** [comment] 2015-01-12 15:58
@jnothstine good catch.  This does indeed appear to be a duplicate of that issue.  Thanks!

**Closed** 2015-01-12 15:58 UTC
Labels: Bug, Duplicate, Resharper
