### ISSUE TITLE
Detection of the current selection seems to fail with using other extensions

### ISSUE THREAD

**Issue by MartinL0815** [jaredpar/VsVim#1842] opened 2016-09-30 06:50 UTC
1. When I select a few lines and use e.g. the "Code alignment" extension than always the next line below the last selected line will be used, too. This issue occurred from time to time after updating VsVim and got fixed from time to time.
2. When I place the caret in a word and press the accelerator for "Entrian Source Search" to start a search, longer words loose their last character. This issue got introduced in the last release, while "Entrian Source Search" was not updated.

Currently I use VsVim 2.1.1.0.

**Comment by jaredpar** [comment] 2016-10-09 14:17
Thanks for reporting.  The second issue should be fixed in the latest sources.  I will take a look at the first one.

**Comment by ricksladkey** [comment] 2018-05-21 05:07
In my opinion this is a bug in the code alignment extension. You can reproduce the problem without VsVim by simple dragging directly down in the far left margin so that you include the line break of the last selected line. This is the same selection that `V` produces.

In other words, even though the selection does not include any characters from the subsequent line, the code alignment extension is reformatting the subsequent line. This is an "off by one" bug where it should consider which line the last character in the selection belongs to, not line that the first character *after* the selection belongs to.

**Comment by ricksladkey** [comment] 2018-09-19 19:00
Because the VsVim behavior in question cannot be changed without sacrificing compatiability with vim, and because the issue can be reproduced in the code alignment extension without involving VsVim, I am closing this issue.

**Closed by ricksladkey** 2018-09-19 19:00 UTC
Labels: bug
