### ISSUE TITLE
The command ":m .+1" does't work as expected

### ISSUE THREAD

**Issue by eksea** [jaredpar/VsVim#1928] opened 2017-03-02 06:43 UTC
In vim, the command ":m .+1" will move down the current line one line, and the cursor still in the current line(the moved line). But, in vsvim, this command will move down the current line one line, meanwhile, **the cursor move down one more line(the cursor is not in the moved line at all)**.
========update========
There's another problem with this command. If vim is in "VISUAL BLOCK" model, after execute move, vim will exist "VISUAL BLOCK" mode and go into "NORMAL" model. The expected result is that vim is still in "VISUAL BLOCK" mode.

**Comment by sqlkoala** [comment] 2018-01-02 13:21
There is a visual studio shortcut/command to do that: Alt+Downarrow.

If you want, you can call that command from vsvim and define your own mapping:
nnoremap ?? :vsc Edit.MoveSelectedLinesDown<CR>

**Comment by jaredpar** [comment] 2018-01-13 22:21
Looks like a dupe of #1178

**Closed by jaredpar** 2018-01-13 22:21 UTC
Labels: bug
