### ISSUE TITLE
Inserting from visual block mode does not respect tab/space settings

### ISSUE THREAD

**Issue by henrybw** [jaredpar/VsVim#1345] opened 2014-04-05 21:23 UTC
(Observed on version 1.6.0.2)

When performing a multi-line insert from visual block mode, inserting tabs will result in VsVim leaving tab characters for all lines except for the first one, even if expandtab (or the equivalent VS setting) is enabled.

The following example has shiftwidth=2 and tabstop=4 to illustrate the bug. Both expandtab and VS's "Insert Spaces" settings are enabled.
1. Select text in visual block mode:
   
   ![vsvim-tab-bug1](https://cloud.githubusercontent.com/assets/748064/2623796/d7875f92-bd07-11e3-9fe9-921d484ddea7.png)
2. Press Tab:
   
   ![vsvim-tab-bug2](https://cloud.githubusercontent.com/assets/748064/2623799/0ac079f2-bd08-11e3-8767-fd9e0b296bb6.png)
3. Press Esc:
   
   ![vsvim-tab-bug3](https://cloud.githubusercontent.com/assets/748064/2623800/1dcd59fc-bd08-11e3-9af4-e59c25508589.png)

The last two lines that were indented should be aligned with the first line that was indented, but instead the last two lines have a tab character instead of spaces, resulting in them being mismatched.

**Comment by ricksladkey** [comment] 2018-08-08 19:48
This issue is a duplicate of issue #992. The issue was also fixed in PR #2211 and so this issue can be closed.

**Closed** 2018-08-14 03:37 UTC
Labels: bug, duplicate
