### ISSUE TITLE
Implement smart formatting of comments

### ISSUE THREAD

**Issue by hollasch** [jaredpar/VsVim#970] opened 2012-09-12 22:10 UTC
I suppose that this is a backburner sort of item, but I really miss the smart formatting in Vim. For example, entering text in a // comment will not only wrap the line, but will also prepend the line with the appropriate comment syntax. It's also really handy when changing a paragraph comment, as you can use 'gqap' to reflow and recomment the entire paragraph.

Perhaps a limited solution (like gqap, or just insert-mode wrapping) is feasible.

**Comment by jcredland** [comment] 2017-10-07 10:14
This would be amazing.
:)

**Comment by ricksladkey** [comment] 2018-08-08 18:54
The `gq` half of this request was implemented in PR #2274.

**Comment by ricksladkey** [comment] 2018-08-08 19:02
The other half of this request is the `c`, `r` and `o` options of `formatoptions` (see vim `:help fo-table`).

**Comment by ricksladkey** [comment] 2018-08-11 23:09
It turns out this is a duplicate of the older issue #573.

**Closed** 2018-08-16 14:58 UTC
Labels: duplicate, feature request
