### ISSUE TITLE
is it possible to using hjkl to selecting item on the list?

### ISSUE THREAD

**Issue by SugeunOh** [jaredpar/VsVim#2396] opened 2018-10-22 15:21 UTC
![image](https://user-images.githubusercontent.com/17059492/47297708-de4b3a80-d650-11e8-8e24-1a660675b4c0.png)

![image](https://user-images.githubusercontent.com/17059492/47298290-5c5c1100-d652-11e8-855f-12b435756a8f.png)

![image](https://user-images.githubusercontent.com/17059492/47298358-8c0b1900-d652-11e8-8a24-81a01857738e.png)

![image](https://user-images.githubusercontent.com/17059492/47298444-c5438900-d652-11e8-84f2-483ea6aa3bd3.png)

Hi again.
VsVim is so great. 

I'm looking for key binding to selecting item on the list (attached images) instead Up, Down Arrow key.

There is four type of lists.

- list in Text Editor (in vim, ctrl + p - show list, and ctrl + p - moving cursor and select)
- list in Quick Launch
- list in File or Object or Types or ...
- list in Find Results (ctrl + shift + f)

I'm looking for command to key mapping, but I can't find any command for moving cursor key binding.
is it possible to change key binding in these lists?

**Comment by sqlkoala** [comment] 2018-10-28 08:34
I am not 100% sure, but I think I know what you want, because I have done the same.
This is about about configuring VStudio, not Vsvim.
You need to assign a shortcut for Vstudio commands Edit.LineDown and Edit.LineUp.
Like this:
![image](https://user-images.githubusercontent.com/30384885/47613686-2e346200-da94-11e8-8f7a-c6d64aa76646.png)
(i have j/k switched, so you choose Alt+j for Down)
With this, I can use Alt+k/j to navigate intellisense menu. Find List also works.

**Comment by ricksladkey** [comment] 2018-10-29 03:38
@SugeunOh I hope this approach satisfies your needs!

@sqlkoala Thanks for fielding this question. I think your answer covers all relevant points and so I am going to close this issue since it is not a bug in VsVim nor a feature that VsVim can implement.

**Closed by ricksladkey** 2018-10-29 03:38 UTC
