### ISSUE TITLE
i [ESC] A closes currently open file

### ISSUE THREAD

**Issue by Azendale** [jaredpar/VsVim#1563] opened 2015-02-15 02:13 UTC
Leaving insert mode, and then doing a command such as "A" closes the current file.

This does not happen if you do a motion command before the "A" command. So while 'i [ESC] A' closes the current document, 'i [ESC] w A' would not.

This does not seem to be limited to "A", other "insert motion" commands run right after leaving insert trip this. So 'i [ESC] C' will also close the current file.

Interestingly, it appears that the command after [ESC] is executed, but after the current file is closed. So if you have files A & B open, and are working in A, and do 'i [ESC] C', you will find yourself in file B, whereever you were last editing B.

This is happening with VS 2013. I left the VsVim handling vs Visual Studio handling at defaults, (basically, all handled by Visual Studio).

**Comment by Azendale** [comment] 2015-02-15 02:25
Ok, had an idea looking at and writing the original bug report. Did a binary search of the handle with VsVim versus handle with VisualStudio. If handle with Visual Studio is set for Shift+ESC, this bug happens, if it is set to handle with VsVim it does not happen. But I'm not pressing Shift+ESC. (I made myself type one fingered to be sure of this :) ). I'm pressing ESC (letting the ESC key up), then pressing shift.

**Comment by jaredpar** [comment] 2015-02-15 16:30
Thanks for taking the time to file that report. 

That behavior is strange.  I use that pattern quite often and just verified on my machine that it doesn't cause any problems.  The file remains open and VsVim switches to insert mode for the `A` command.

I think the most likely cause here is a function in the vimrc file that is causing a problem.  Could you paste the contents of your vimrc somewhere that I could take a look at?  Also if you disable the vimrc does this problem go away?

**Comment by Azendale** [comment] 2015-02-17 23:06
Sorry it has taken a while to get back to this. I'm not quite sure where to
look for a .vimrc on windows. I can probably figure that out given time,
but I haven't figured it out yet. Where should I be looking?

**Comment by jaredpar** [comment] 2015-02-18 02:45
It would be in your home directory and named _vimrc

U can also just type :set in VS and it should show th path where it loaded
it from.

On Tuesday, February 17, 2015, Erik B. Andersen <notifications@github.com>
wrote:

> Sorry it has taken a while to get back to this. I'm not quite sure where to
> look for a .vimrc on windows. I can probably figure that out given time,
> but I haven't figured it out yet. Where should I be looking?
>
> On Sun, Feb 15, 2015 at 8:30 AM, Jared Parsons <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Thanks for taking the time to file that report.
> >
> > That behavior is strange. I use that pattern quite often and just
> verified
> > on my machine that it doesn't cause any problems. The file remains open
> and
> > VsVim switches to insert mode for the A command.
> >
> > I think the most likely cause here is a function in the vimrc file that
> is
> > causing a problem. Could you paste the contents of your vimrc somewhere
> > that I could take a look at? Also if you disable the vimrc does this
> > problem go away?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jaredpar/VsVim/issues/1563#issuecomment-74424257>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaredpar/VsVim/issues/1563#issuecomment-74775045>.
>


-- 
Jared Parsons
http://blog.paranoidcoding.com/
http://twitter.com/jaredpar

**Comment by Azendale** [comment] 2015-02-18 03:09
Thanks. That helped a lot.

It is trying to load from C:\Users\erik;C:\Users\erik

I looked in that folder and there are no files (only folders). I have
windows explorer set to show hidden files.

One thought -- I've used keytweek to make capslock escape and escape
capslock (as a Vim user, you probably understand my thinking there). I also
use the Dvorak layout. I wouldn't think that would have any effect, but
maybe it would (but then why would everything else work?).

**Comment by jaredpar** [comment] 2015-02-22 15:31
I've tried for a bit to reproduce this and can't find a way.  I've gone back to the setup which appears closest to yours:

- Reset every key to be handled by Visual Studio.  In this mode `Shift + ESC` is handled by Window.CloseToolWindow.
- Disabled my _vimrc file. 

Still I'm unable to reproduce this.  Tried mostly to repro in C# class library projects.

**Comment by jaredpar** [comment] 2018-01-09 18:23
Closing due to staleness

**Closed by jaredpar** 2018-01-09 18:23 UTC
Labels: need more data
