### ISSUE TITLE
Save selection not working properly (  :'<,'>w FILENAME  )

### ISSUE THREAD

**Issue by Luxsi** [jaredpar/VsVim#1785] opened 2016-05-29 20:34 UTC
I'm somewhat new to Vim, but from what I learned in Vimtutor I think this is a bug;
When you select text either with _**v**_ or the mouse and type the command _**:'<,'>w FILENAME**_ (the first part being automatic), it's expected to save the selection into a file, but instead it saves the _entire_ document into _**FILENAME**_.

Having it fixed would help with, for example, creating templates that you can then call with _**:r FILENAME**_

**Comment by ricksladkey** [comment] 2018-07-22 18:59
This feature was implemented in PR #2200 and so this issue can be closed.

Related to and a duplicate of #428.

**Closed** 2018-08-22 17:43 UTC
Labels: feature request
