### ISSUE TITLE
replacing text with char search replaces former regular char search

### ISSUE THREAD

**Issue by MartinL0815** [jaredpar/VsVim#1985] opened 2017-08-17 12:06 UTC
Hi,

If I do "regularly" `'tA'` to search for the character `'A'` and replace from this starting point some text with `'cfC'`, then the former regular search `'tA'` cannot be repeated anymore, so that a combination of `';.'` to step in a line through occurrences of `'A'` and to repeat the replacement is not possible.

In VIM this is the normal behavior I know since years, but may - naturally unknown - depend on settings.

Could you please take a look and fix it - if desirable?

Best regards,

Martin

**Comment by ricksladkey** [comment] 2018-06-13 00:15
@MartinL0815 I cannot reproduce the behavior you describe in vim and it is counter to the vim documentation for `;`:

> Repeat latest f, t, F or T [count] times.

Can you describe a concrete test case that works in vim and doesn't work in VsVim?

**Comment by MartinL0815** [comment] 2018-06-13 07:33
Hi @ricksladkey,
I just wondered why you can't reproduce the described behavior in vim, since this was a normal workflow for me and … in the current installed version (8.0.586) of vim I can't reproduce it, too.
Could the experienced behavior depend on a setting/configuration in ViM?
I found it quiet handy, that the current searched character was not identical to the one used in a command.
As I already wrote - I used this scheme regularly, like `tacfo…<Esc>;.;.;.;.…` to replace repeated text in a line.
At the time of reporting this issue, I was able to reproduce the behavior, today I'm not.

**Comment by ricksladkey** [comment] 2018-12-20 05:49
Closing this as no longer reproducible.

**Closed by ricksladkey** 2018-12-20 05:49 UTC
Labels: bug
