### ISSUE TITLE
matchpairs appears to not be implemented

### ISSUE THREAD

**Issue by jnothstine** [jaredpar/VsVim#1255] opened 2014-01-20 15:52 UTC
In gvim, I can set matchpairs like this:

set matchpairs=(:),{:},[:],<:>

and the % key will match the appropriate item.  Right now, % will match on (:) or {:} or [:] but it doesn't match <:>.  This is a nice feature when editing xaml code.  I only add <:> to matchpairs but gvim lets you add any pair you want.

Thanks,

Jerry.

**Comment by jaredpar** [comment] 2018-01-09 05:33
Looks like a dupe of #810

**Closed by jaredpar** 2018-01-09 05:33 UTC
Labels: feature request
