### ISSUE TITLE
Macro recording, missing characters

### ISSUE THREAD

**Issue by KLIM8D** [jaredpar/VsVim#1670] opened 2015-09-14 06:54 UTC
Hi,

When I've recorded a macro and it includes the characters ")" and/or "}", they are left out when I replay the macro.

Example:

```
if(true)
{
    string s = "test";
}
```

Then replaying the macro, gives me
```
if(true
{
    string s = "test";
```

**Comment by jaredpar** [comment] 2015-09-15 03:46
Thanks for reporting.  This looks like a duplicate of #1629.  Essentially the IDE is auto completing those characters and hence VsVim doesn't see the key strokes to intercept them.  As a result they don't get replayed on the subsequent macro run.  

Recently I had an idea on how to fix this.  Going to tryi this out in the next release.

**Closed by jaredpar** 2015-09-15 03:46 UTC
