### ISSUE TITLE
Pasting in VS2019 with p after yanking  takes almost a full second.

### ISSUE THREAD

**Issue by kabasakalis** [jaredpar/VsVim#2483] opened 2019-04-07 09:19 UTC
That's a serious lag. Please thumbs up if you have experienced this in VS2019 with VsVim.
Ctrl+C and Ctrl+V is instantaneous as expected.

**Comment by jaredpar** [comment] 2019-04-08 02:43
@kabasakalis that definitely shouldn't be happening. I use VS2019, many different builds, daily at work and don't see this. 

Can you grab a profile of VS when this happens and share it out? That should help narrow down what is going on here.

**Comment by kabasakalis** [comment] 2019-04-08 16:39
I am running a single main function that calculates a Fibbonacci number. Nothing fancy. This is the CPU profile for the 2 breakpoints shown. It doesn't matter if I am in debug mode or not, the lag is always there.
![image](https://user-images.githubusercontent.com/323951/55741491-07605b80-5a36-11e9-8234-9a3dcaf08e84.png)

**Comment by kabasakalis** [comment] 2019-04-08 16:57
Update! There's something wrong with my custom `vimrc` file. When I don't load it, the lag goes away! I wish there was a VsVim log so I could pinpoint the problem easier. Commenting out suspicious parts of my vimrc will do it I guess.

**Comment by jaredpar** [comment] 2019-04-08 17:19
@kabasakalis 

Glad you could track it down. Can you post the part of the RC file that caused the problem? Likely a parsing gap. If it's easy to fix would like to fix it.

**Comment by kabasakalis** [comment] 2019-04-08 17:28
Actually I haven't  debugged it yet - feeling a little lazy right now. But here's the file

[_vsvimrc.txt](https://github.com/jaredpar/VsVim/files/3055573/_vsvimrc.txt)

**Comment by TKumadaki** [comment] 2019-04-23 15:37
I delete the following your settings in my environment.
There is no delay.

`map  pd :vsc Edit.PeekDefinition<CR>`

I think probably waiting for input has occurred.
Is this not normal?

**Comment by ricksladkey** [comment] 2019-04-23 16:31
Since @TKumadaki found the root cause of the delay (map ambiguity with prefix `p`), I am closing this as resolved.

**Closed by ricksladkey** 2019-04-23 16:31 UTC
Labels: bug
