### ISSUE TITLE
Significant delay when typing

### ISSUE THREAD

**Issue by mjibson** [jaredpar/VsVim#1104] opened 2013-06-03 23:48 UTC
For the past year, on Windows 7 and 8, on a fast desktop and macbook pro, VsVim seems to be related to some problem that causes Visual Studio 2012 (and I believe 2010 at the time, as well) to hang for 1-5 seconds after typing any character. This happens in both command and insert modes. It appears to be working, and sometimes it will process characters quickly after some initial delay. There are 9 extensions installed and Resharper makes a 10th. No one else on my team reports this problem, and many of them have the same extensions installed, less VsVim, so I don't believe it's caused by our codebase size or extension combination. Even under best circumstances, there is still a visual delay before characters appear on the screen. When searching with `/`, if the next result requires the buffer to scroll, it takes ~1s to display (`zz` has a similar issue). All other commands have similar latencies. It is unbearable coming from the instantaneous gvim.

Is there anything I can do to provide you with a way to debug this?

**Comment by rytmis** [comment] 2015-05-12 09:10
I've experienced this as well -- there's a clearly noticeable delay in everything when the Git SCM provider and VsVim work together.

Also, and I'm not sure if this is related, sometimes when the undo buffer gets very large, typing a single `u` first hangs VS for about a minute, then undoes practically the entire edit session (even when earlier, it would have undone in smaller increments). `Ctrl+R` will restore the changes.

**Comment by jaredpar** [comment] 2015-05-13 20:24
@rytmis It's nice to confirm that the Git SCM interaction is the cause of this behavior.  Obviously this is something that needs to be fixed but even tracknig it down to this has been a large problem. 

I'm really interested in the undo buffer case.  There have been a few bugs around this in the past but they've been largely patched in the most recent versions.  What version of VsVim are you using?  Are there any particular scenarios where this occurs?

**Comment by rytmis** [comment] 2015-05-13 21:48
1.8.0.0, but I'm fairly sure I've had the same happen in earlier versions, too. 

So far, I haven't found a way to intentionally reproduce the problem, it'll just happen once or twice a week. Off the top of my hat, I'd say it's usually a case of having a longer session in insert mode after multiple smaller edits.

Do you think it'd be useful to get a trace from a regular editing session with the Git provider enabled? If it is something I can just do ad-hoc when I encounter the problem, I think I might be able to pull it off at some point.

**Comment by jaredpar** [comment] 2015-05-14 18:26
If you could get a trace that would be amazing. One of the biggest issues
I've had with this bug is getting a trace for it.

On Wednesday, May 13, 2015, Lauri Kotilainen <notifications@github.com>
wrote:

> 1.8.0.0, but I'm fairly sure I've had the same happen in earlier versions,
> too.
>
> So far, I haven't found a way to intentionally reproduce the problem,
> it'll just happen once or twice a week. Off the top of my hat, I'd say it's
> usually a case of having a longer session in insert mode after multiple
> smaller edits.
>
> Do you think it'd be useful to get a trace from a regular editing session
> with the Git provider enabled? If it is something I can just do ad-hoc when
> I encounter the problem, I think I might be able to pull it off at some
> point.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaredpar/VsVim/issues/1104#issuecomment-101825887>.
>


-- 
Jared Parsons
http://blog.paranoidcoding.com/
http://twitter.com/jaredpar

**Comment by rytmis** [comment] 2015-05-15 08:33
Hmm. In my limited experience, the perf issue usually doesn't manifest immediately after a fresh start, and the feedback tool apparently wants to restart VS before the traces are enabled.

**Comment by jaredpar** [comment] 2018-01-02 20:16
Closing due to staleness

**Closed by jaredpar** 2018-01-02 20:16 UTC
Labels: bug
