### ISSUE TITLE
vim's 'H' command doesn't work properly when it's preceeded with a number

### ISSUE THREAD

**Issue by nexusoeama** [jaredpar/VsVim#1636] opened 2015-07-16 00:51 UTC
Something is wrong with the 'H' command.

For example if you type in '5H' while in normal mode, the cursor should jump to the 5th line from the top of the current editor's view. However, for me it almost always jumps to the 1st line, as though you didn't type the '5' - just ignoring the preceded number.

Interestingly, if you type '5H' followed by another '5H', the cursor first jumps to the first line, then jumps to the 5th line. So if you test, test from an initial cursor position near the middle or end of the view.

**Comment by jaredpar** [comment] 2015-07-20 16:05
It looks like this is a duplicate of #1637.  Going to let that one be the primary.

**Closed by jaredpar** 2015-07-20 16:05 UTC
