### ISSUE TITLE
Mouse selecting from right to left missing the last char.

### ISSUE THREAD

**Issue by xuboying** [jaredpar/VsVim#1801] opened 2016-06-30 14:40 UTC
Version 2.1.1.0
VS: 2013 VC++
Mouse selecting from right to left missing the last char(most right char).

**Comment by jaredpar** [comment] 2016-06-30 15:45
Thanks for reporting.  I will take a look at this.

**Comment by xuboying** [comment] 2016-07-01 03:10
Thanks!

**Comment by slav** [comment] 2016-07-31 19:00
This is also happening on VS 2015

**Comment by ricksladkey** [comment] 2018-05-22 22:59
Unless I am misunderstanding something, I cannot currently reproduce this bug, with either `behave=mswin` or `behave=xterm`.

**Comment by ricksladkey** [comment] 2018-07-21 05:37
I now understand this bug better and know that it was caused by a previous change that was reverted by PR #1829, which was merged, so this can be closed.

**Closed** 2018-07-21 15:45 UTC
Labels: feature request, visual studio integration
