### ISSUE TITLE
switch windows ctrl + ww

### ISSUE THREAD

**Issue by geoff3jones** [jaredpar/VsVim#1079] opened 2013-04-11 13:01 UTC
feature request:

Would it be possible to add the window switching like "ctrl + ww" does when you create a split in normal vim? I guess the functionality equivalent would cycle cursor focus between editor windows/panels? ps love this extention <3

**Comment by jaredpar** [comment] 2018-01-01 18:44
Closing as a duplicate of #625

**Closed by jaredpar** 2018-01-01 18:44 UTC
Labels: feature request
