### ISSUE TITLE
Wrong symbol for 'gd'

### ISSUE THREAD

**Issue by noscript** [jaredpar/VsVim#1754] opened 2016-03-07 10:13 UTC
VsVim has a deviant behavior from Vim. It fails to properly extract the word under cursor for "go to definition" movement.

Doing `gd` there (marked the cursor location as `|`):

``` cpp
MyO|bject* object;
```

fails with:

```
A definition for the symbol 'MyObject*' could not be located.
```

Similar in there:

``` cpp
obj|ect.someMethod();
```

it will try to query `someMethod` instead of `object`.

**Comment by noscript** [comment] 2016-03-07 10:39
VS has two suitable functions to make an equivalent for `gd` but they require an argument (#1516)
```
Edit.FindSymbol
Edit.QuickFindSymbol
```

**Comment by jaredpar** [comment] 2018-01-12 04:38
Looks like a dupe of #1593.

**Closed by jaredpar** 2018-01-12 04:38 UTC
