### ISSUE TITLE
Completion Mode (Ctrl-X in insert mode)

### ISSUE THREAD

**Issue by ijcuevas2** [jaredpar/VsVim#1718] opened 2015-12-20 12:12 UTC
I don't know if this is already supported. VsVim should support line completion as in regular vim. For example, using the Ctrl-X Ctrl-L shortcut in insert mode to autocomplete lines is quite useful.

**Comment by awojcik-lgnexera** [comment] 2016-02-19 07:56
Yes, this would be very useful. Or maybe this is already implemented but some configuration is needed?

**Comment by farzadmf** [comment] 2016-10-14 20:28
I like Ctrl-X feature in vim A LOT. It would be so nice if it would work here ...

**Comment by ricksladkey** [comment] 2018-08-15 21:16
This is a duplicate of issue #1718 and so this issue can be closed.

**Closed** 2018-08-16 03:17 UTC
Labels: feature request

**Comment by dtynewydd** [comment] 2020-04-29 08:56
> This is a duplicate of issue #1718 and so this issue can be closed.

Am I crazy or is the lissue linked *this* issue? Did this ever get implemented?

**Comment by wayneforrest** [comment] 2025-01-06 03:47
> This is a duplicate of issue #1718 and so this issue can be closed.

Perhaps that reference number is not correct, this issue itself is #1718 (a circular references)
