### ISSUE TITLE
Command characters present at the right side of the command margin

### ISSUE THREAD

**Issue by wavebit** [jaredpar/VsVim#2415] opened 2018-11-10 09:13 UTC
'25g' should present at the left side.
![cap1](https://user-images.githubusercontent.com/11334491/48299688-63689780-e50b-11e8-89e0-7ec6edbb0b72.png)

It works right in last line mode.
![cap2](https://user-images.githubusercontent.com/11334491/48299697-7b401b80-e50b-11e8-8119-d2c7d5d2a369.png)

VsVim 2.6.0.0
Visual Studio 15.8.8

**Comment by ricksladkey** [comment] 2018-11-10 22:13
This is by design and is the same way that vim/gvim works.

When you type `25g` as part of a normal mode command, the vim/VsVim setting `:set showcmd` controls whether this partial command is displayed on the right hand side of the command margin.

However, when you type `:marks` you are in command mode and there is a caret that indicates where your typing will be inserted. In this case the text starts on the left.

**Comment by wavebit** [comment] 2018-11-10 23:17
Sorry, i don't use gvim/vim usually. 
I like the normal mode command to show on the left as before in VsVim. So, how to set it?

**Comment by ricksladkey** [comment] 2018-11-11 03:07
VsVim did not previously support this feature and so it has never been shown on the left. It was only introduced in VsVim 2.6.0. Since vim puts it on the right, VsVim also puts it on the right. To allow it to be put at the left would require adding a vim-incompatible setting.

As a result, the only available options are:

1) Restore the previous VsVim behavior (no feedback at all) with the setting `:set noshowcmd`
2) Use the default setting `:set showcmd` and have the normal command feedback on the right

**Closed** 2018-11-11 03:29 UTC

**Comment by wavebit** [comment] 2018-11-11 05:36
Great! That will be better for widescreen and multi-screen.

**Comment by dhmgit** [comment] 2018-11-13 02:05
> @wavebit If what you say is true, I stand corrected! Perhaps @dhmgit can comment.

It is true that in version VsVim 2.5, *some* partially entered commands would be displayed left-justified as shown above. This was, however, inconsistent, only partially implemented, and did not match gVim's behavior. Sometimes the text would be shown by itself, sometimes it was appended to the mode text, and sometimes it was missing entirely. The intent of the changes in 2.6 was to mimic the gVim `showcmd` feature as faithfully as possible.

So is the feature request to add a non-standard Vim option to left-justify the `showcmd` text?  

For example:

![image](https://user-images.githubusercontent.com/3457284/48385803-e9c4db00-e6bd-11e8-9d92-507d9b5e830f.png)

And with mode text:

![image](https://user-images.githubusercontent.com/3457284/48385776-d0bc2a00-e6bd-11e8-9209-0e84e0464059.png)

**Comment by TKumadaki** [comment] 2019-05-03 22:35
Hi @wavebit
Perhaps @dhmgit may be waiting for your response.
By the way,Same as you,I wanted to display command characters in an easy-to-see place.
So I created the following script.

https://github.com/TKumadaki/VsVimScripts/blob/master/Documentation/ShowCommandText.md

This will display Command Characters below the caret.
It will be as follows.

![Command characters](https://user-images.githubusercontent.com/38175836/57168818-8763c080-6e3e-11e9-85f0-6f1dde0af6df.png)

This script works with VsVim 2.7.
