### ISSUE TITLE
Recursive macros: Appending to a macro incorrectly stores calls to the macro itself

### ISSUE THREAD

**Issue by mfrischknecht** [jaredpar/VsVim#2173] opened 2018-06-01 11:53 UTC
Recursive macros are really useful for performing similar edits on big input. There are multiple ways to record a recursive macro. After I encountered the error described below (using the appending method), I discovered that an alternative method (pre-emptying a macro and calling it during the first recording) actually is already working in VsVim. So the feature itself seems to be there already.

## Not working in VsVim

Given for example this input (using | for the cursor):

```
foobar1|
foobar2
foobar3
foobar4
foobar5
```

We record a macro on the first line: `qq0frabaz<ESC>j`. After this, the cursor is on the second line:

```
foobarbaz1
foobar2|
foobar3
foobar4
foobar5
```

To make our macro recursive, we should then be able to append to it: `qQ@qq`, which runs it also on the second line:

```
foobarbaz1
foobarbaz2
foobar3|
foobar4
foobar5
```

If we then run the macro again on the third line using `@q`, it should process the rest of the file. In VsVim, however, it still only processes one line at a time.

Comparing the output of `:reg`, we can see that the content of `"q` in VsVim looks like this: `0frabazj@0frabazjq`  (as a sidenote: it seems like the VsVim status bar hides the `^[` representing the escape before the `j`).
The 'correct' register content (according to Vim) instead would be: `0frabaz^[j@q`. It seems as if the execution of `"q` within the appending recording leads to all keystrokes within the macro also being stored in the register between `@` and the register `q` (instead of only the macro execution command `@q`).

## Working correctly in VsVim

Currently, one working alternative is to pre-empty the register (using `qqq`) and call it within the first recording "session":

```
foobar1|
foobar2
foobar3
foobar4
foobar5
```

With the cursor on the first line, the keystrokes `qqqqq0frabaz<ESC>j@qq` record a recursive macro:

```
foobarbaz1
foobar2|
foobar3
foobar4
foobar5
```

`:reg` shows the correct content of `"q`: `0frabazj@q`. Running the macro on the second line after that using `@q` correctly processes the whole file. This seems to work because the `"q` register was initially empty, thus the bug described above doesn't impact the `@q` sequence in the macro.

**Comment by ricksladkey** [comment] 2018-06-01 16:11
This is a duplicate of issue #2119.

**Closed** 2018-06-02 17:01 UTC
