### ISSUE TITLE
Dot completion woes

### ISSUE THREAD

**Issue by ssmith73** [jaredpar/VsVim#1926] opened 2017-02-28 10:02 UTC
Great work - i use this plugin everyday - apologies if this has been mentioned before.

Dot '.' repeat does not work for me if i use intellisence completion on the previous command (the command i want to repeat), it only completes what i actually typed, rather than the completed form. Is this something i'm doing badly or is it a known issue?

**Comment by jaredpar** [comment] 2018-01-13 22:20
Thanks for reporting. Closing as a dupe of #664.

**Closed by jaredpar** 2018-01-13 22:20 UTC
